# Generated by Django 2.0.4 on 2018-04-28 11:17

from django.db import migrations, models
import django.db.models.deletion
import helpers.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bussiness_name', models.CharField(max_length=64)),
                ('tax_id', models.CharField(max_length=64)),
                ('email_contact', models.CharField(max_length=64)),
                ('phone_contact', models.CharField(max_length=64)),
                ('legal_respresentative', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=helpers.files.upload_to_generic)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.DocumentType')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
