# Generated by Django 2.0.4 on 2018-04-28 11:56

from django.db import migrations, models
import helpers.files


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20180428_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_contact',
            field=models.EmailField(max_length=64),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='file',
            field=models.FileField(upload_to=helpers.files.upload_to_generic),
        ),
    ]
