# Generated by Django 2.0.4 on 2018-04-29 19:48

from django.db import migrations, models
import helpers.files


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20180429_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='error_url',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='success_url',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='file',
            field=models.FileField(upload_to=helpers.files.upload_to_generic),
        ),
    ]
