# Generated by Django 2.0.4 on 2018-04-30 14:09

from django.db import migrations, models
import helpers.files


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20180429_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sign',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='file',
            field=models.FileField(upload_to=helpers.files.upload_to_generic),
        ),
    ]
