# Generated by Django 2.0.4 on 2018-04-30 18:41

from django.db import migrations, models
import helpers.files


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20180430_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='photo',
            field=models.ImageField(default='', upload_to=helpers.files.upload_to_generic),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'not verified'), (1, 'verified')], default=0),
        ),
        migrations.AlterField(
            model_name='companydocument',
            name='file',
            field=models.FileField(upload_to=helpers.files.upload_to_generic),
        ),
    ]
