# Generated by Django 2.0.4 on 2018-04-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthentiaBaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenUserModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('key', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthentiaDefaultUser',
            fields=[
                ('authentiabaseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AuthentiaBaseUser')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('is_admin', models.BooleanField(default=False)),
                ('token', models.OneToOneField(max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_token', to='users.TokenUserModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.authentiabaseuser', models.Model),
        ),
        migrations.CreateModel(
            name='AuthentiaUser',
            fields=[
                ('authentiabaseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AuthentiaBaseUser')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('is_admin', models.BooleanField(default=False)),
                ('token', models.OneToOneField(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='users.TokenUserModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.authentiabaseuser', models.Model),
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('authentiabaseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.AuthentiaBaseUser')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('is_admin', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('token', models.OneToOneField(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user_token', to='users.TokenUserModel')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.authentiabaseuser', models.Model),
        ),
        migrations.AddField(
            model_name='authentiabaseuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='authentiabaseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
