# Generated by Django 2.0.4 on 2018-04-28 11:37

from django.db import migrations, models
import django.db.models.deletion
import helpers.files


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=helpers.files.upload_to_generic)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.DocumentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AuthentiaUser')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
