# Generated by Django 2.0.4 on 2018-04-28 14:54

from django.db import migrations, models
import django.db.models.deletion
import helpers.files


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180428_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(upload_to=helpers.files.upload_to_generic),
        ),
    ]
