# Generated by Django 2.0.4 on 2018-04-28 17:36

from django.db import migrations, models
import django.db.models.deletion
import helpers.files


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180428_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to=helpers.files.upload_to_generic)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AuthentiaUser')),
            ],
            options={
                'abstract': False,
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(upload_to=helpers.files.upload_to_generic),
        ),
    ]
